version = 1

[update]
always = false
require_automerge_label = true

[merge]
method = "squash"
automerge_label = "automerge"
block_on_neutral_required_check_runs = true

[merge.message]
title = "pull_request_title"
body = "pull_request_body"
include_pr_number = true
body_type = "markdown"
strip_html_comments = true
include_coauthors = true
