version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: bun
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: America/Chicago
    open-pull-requests-limit: 100
    groups:
      better-auth:
        patterns:
          - "better-auth"
          - "@better-auth/*"
      eslint:
        patterns:
          - "@eslint/*"
          - "eslint"
      expo:
        patterns:
          - "expo"
          - "expo-*"
          - "@expo/*"
      trpc:
        patterns:
          - "@trpc/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
      timezone: America/Chicago
    open-pull-requests-limit: 100

  - package-ecosystem: gradle
    directory: "/apps/client"
    schedule:
      interval: daily
      time: "04:00"
      timezone: America/Chicago
    open-pull-requests-limit: 100
