version: 2

updates:
  - package-ecosystem: bun
    directory: "/"
    schedule:
      interval: daily
      time: 04:00
      timezone: America/Chicago
    open-pull-requests-limit: 100

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: 04:00
      timezone: America/Chicago
    open-pull-requests-limit: 100
