name: Setup Bun
description: Setup Bun and Install Dependencies

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979 # v2
      with:
        bun-version-file: ".bun-version"
    - name: Install Dependencies
      shell: bash
      run: bun install --frozen-lockfile
