name: Build Server

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
    tags:
      - 'v*'

concurrency:
  # Only cancel in-progress runs for pull_request events
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  # we use this so that required checks work properly
  should-skip:
    runs-on: self-hosted
    permissions:
      contents: read
      actions: write
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1
        with:
          paths: '["apps/server/**", "packages/schemas/**", "packages/source-tap/**", "Dockerfile", ".dockerignore", ".github/workflows/build-server.yml", ".github/actions/setup-bun/action.yml"]'
          cancel_others: 'false'
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'false'

  build-server:
    runs-on: ubuntu-latest

    needs:
      - should-skip

    if: needs.should-skip.outputs.should_skip != 'true'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=auto
          tags: |
            ${{ github.event_name == 'pull_request' && format('type=sha,prefix=pr-{0}-sha-', github.event.pull_request.number) || 'type=sha' }}
            type=ref,event=tag
            type=ref,event=pr,prefix=pr-
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge,branch=main
      - name: Get Sharp Version from package.json
        working-directory: apps/server
        run: |
          echo "SHARP_VERSION=$(cat package.json | jq -r '.dependencies.sharp')" >> $GITHUB_ENV
      - name: Build image
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          layers: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          containerfiles: |
            ./Dockerfile
          build-args: |
            SHARP_VERSION=${{ env.SHARP_VERSION }}
          extra-args: |
            --isolation=chroot
            --storage-driver=vfs
      - name: Push image
        env:
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$REGISTRY_PASSWORD" | buildah login ghcr.io -u $REGISTRY_USERNAME --password-stdin
          while IFS= read -r tag; do
            echo "Pushing tag: $tag"
            buildah push --storage-driver=vfs $tag docker://$tag
          done <<< $DOCKER_METADATA_OUTPUT_TAGS
