name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
    tags:
      - 'v*'
  merge_group:

concurrency:
  # Only cancel in-progress runs for pull_request events
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build-android-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Decode Signing Keystore
        working-directory: ./apps/client
        run: echo $VOEL_ANDROID_APP_JKS_FILE | base64 --decode > app.voel.android.jks
        env:
          VOEL_ANDROID_APP_JKS_FILE: ${{ secrets.VOEL_ANDROID_APP_JKS_FILE }}
      - name: Generate Native Module
        working-directory: ./apps/client
        run: bun run prebuild --platform android
      - name: Build Android Release App
        working-directory: ./apps/client/android
        run: chmod +x ./gradlew && NODE_ENV=production ./gradlew assembleRelease --no-daemon -Dorg.gradle.caching=true -Dorg.gradle.configuration-cache=true -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs=-Xmx4g
        env:
          VOEL_ANDROID_APP_JKS_PASSWORD: ${{ secrets.VOEL_ANDROID_APP_JKS_FILE }}
      - name: Build Android Debug App
        working-directory: ./apps/client/android
        run: chmod +x ./gradlew && NODE_ENV=development ./gradlew assembleDebug --no-daemon -Dorg.gradle.caching=true -Dorg.gradle.configuration-cache=true -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs=-Xmx4g
        env:
          VOEL_ANDROID_APP_JKS_PASSWORD: ${{ secrets.VOEL_ANDROID_APP_JKS_FILE }}
      - name: Upload Android App
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: apps/client/android/app/build/outputs/apk/(release|debug)/**.apk
          if-no-files-found: error
          retention-days: 7
