name: Build Client

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
    branches:
      - "*"
  push:
    branches:
      - main
    tags:
      - "v*"

concurrency:
  # Only cancel in-progress runs for pull_request events
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  # we use this so that required checks work properly, and so that PR merge commits don't trigger builds again
  should-skip:
    runs-on: self-hosted

    if: (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'build-client')) || github.event_name == 'push'

    permissions:
      contents: read
      actions: write

    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5.3.1
        with:
          # We don't need to build the client when server changes
          # even though it is in the package.json because only types
          # are imported. A typecheck should be good enough.
          paths: '["apps/client/**", "packages/schemas/**", ".github/workflows/build-client.yml", ".github/actions/setup-bun/action.yml"]'
          cancel_others: "false"
          concurrent_skipping: "never"
          skip_after_successful_duplicate: "true"

  android-app:
    runs-on: self-hosted

    needs:
      - should-skip

    if: needs.should-skip.outputs.should_skip != 'true'

    steps:
      - name: Checkout repo
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: "lts/*"

      - name: Generate Debug Runtime Version
        id: debug-runtimeversion
        working-directory: apps/client
        env:
          RELEASE_CHANNEL: development
          VOEL_ANDROID_APP_JKS_PASSWORD: ${{ secrets.VOEL_ANDROID_APP_JKS_PASSWORD }}
          NODE_ENV: development
        run: |
          HASH="$(bun run --silent runtimeversion:android)"
          echo "Debug runtime version is: $HASH"
          echo "hash=$HASH" >> "$GITHUB_OUTPUT"

          if wget --quiet --spider https://artifacts.voel.app/debug/android/$HASH/app-arm64-v8a-debug.apk ; then
            echo "Debug Android APKs for this runtime version exist"
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "Debug Android APKs for this runtime version do not exist"
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate Preview Runtime Version
        id: preview-runtimeversion
        working-directory: apps/client
        env:
          RELEASE_CHANNEL: preview
          VOEL_ANDROID_APP_JKS_PASSWORD: ${{ secrets.VOEL_ANDROID_APP_JKS_PASSWORD }}
          NODE_ENV: production
        run: |
          HASH="$(bun run --silent runtimeversion:android:preview)"
          echo "Preview runtime version is: $HASH"
          echo "hash=$HASH" >> "$GITHUB_OUTPUT"

          if wget --quiet --spider https://artifacts.voel.app/preview/android/$HASH/app-arm64-v8a-release.apk ; then
            echo "Preview Android APKs for this runtime version exist"
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "Preview Android APKs for this runtime version do not exist"
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup JDK 17
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        if: steps.debug-runtimeversion.outputs.exists == 'false' || steps.preview-runtimeversion.outputs.exists == 'false'
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
        if: steps.debug-runtimeversion.outputs.exists == 'false' || steps.preview-runtimeversion.outputs.exists == 'false'
        with:
          cache-read-only: false

      - name: Setup Android SDK
        uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407 # v3
        if: steps.debug-runtimeversion.outputs.exists == 'false' || steps.preview-runtimeversion.outputs.exists == 'false'
        with:
          packages: ""

      - name: Find ccache directory
        id: ccache-dir-path
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        if: steps.debug-runtimeversion.outputs.exists == 'false' || steps.preview-runtimeversion.outputs.exists == 'false'
        with:
          result-encoding: string
          script: |
            const os = require('os');
            const path = require('path');
            return path.join(os.homedir(), '.cache', 'ccache');

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@5ebbd400eff9e74630f759d94ddd7b6c26299639 # v1.2.20
        if: steps.debug-runtimeversion.outputs.exists == 'false' || steps.preview-runtimeversion.outputs.exists == 'false'
        with:
          create-symlink: false
          key: ${{ runner.os }}-${{ github.job }}
        env:
          CCACHE_DIR: ${{ steps.ccache-dir-path.outputs.result }}

      - name: Configure ccache
        if: steps.debug-runtimeversion.outputs.exists == 'false' || steps.preview-runtimeversion.outputs.exists == 'false'
        run: |
          /usr/bin/ccache --set-config=compiler_check="%compiler% --version"
          /usr/bin/ccache -p

      - name: Find Metro Cache
        id: metro-cache-dir-path
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        if: steps.debug-runtimeversion.outputs.exists == 'false' || steps.preview-runtimeversion.outputs.exists == 'false'
        with:
          result-encoding: string
          script: |
            const os = require('os');
            const path = require('path');
            return path.join(os.tmpdir(), 'metro-cache');

      - name: Restore Metro cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        if: steps.debug-runtimeversion.outputs.exists == 'false' || steps.preview-runtimeversion.outputs.exists == 'false'
        with:
          path: ${{ steps.metro-cache-dir-path.outputs.result }}
          key: metro-cache-${{ runner.os }}-${{ github.job }}-${{ github.sha }}
          restore-keys: |
            metro-cache-${{ runner.os }}-${{ github.job }}-

      - name: Decode Signing Keystore
        if: steps.debug-runtimeversion.outputs.exists == 'false' || steps.preview-runtimeversion.outputs.exists == 'false'
        working-directory: apps/client
        run: echo $VOEL_ANDROID_APP_JKS_FILE | base64 --decode > app.voel.android.jks
        env:
          VOEL_ANDROID_APP_JKS_FILE: ${{ secrets.VOEL_ANDROID_APP_JKS_FILE }}

      # - name: Generate Native Debug Module
      #   if: steps.debug-runtimeversion.outputs.exists == 'false'
      #   working-directory: apps/client
      #   run: bun run prebuild --platform android --clean

      # - name: Build Android Debug Assets
      #   if: steps.debug-runtimeversion.outputs.exists == 'false'
      #   working-directory: apps/client/android
      #   run: |
      #     chmod +x ./gradlew
      #     ./gradlew assembleDebug --build-cache --parallel --stacktrace -Dorg.gradle.jvmargs=-Xmx6144M # build apk
      #     ./gradlew bundleDebug --build-cache --parallel --stacktrace -Dorg.gradle.jvmargs=-Xmx6144M # build aab
      #   env:
      #     RELEASE_CHANNEL: development
      #     VOEL_ANDROID_APP_JKS_PASSWORD: ${{ secrets.VOEL_ANDROID_APP_JKS_PASSWORD }}
      #     CMAKE_C_COMPILER_LAUNCHER: /usr/bin/ccache
      #     CMAKE_CXX_COMPILER_LAUNCHER: /usr/bin/ccache
      #     NODE_ENV: development

      # - name: Upload Debug Android Assets
      #   if: steps.debug-runtimeversion.outputs.exists == 'false'
      #   env:
      #     R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      #     R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      #     R2_ENDPOINT: "https://2365912f37ae5914a23644799e325b04.r2.cloudflarestorage.com"
      #     R2_BUCKET: "voel-gh-actions-artifacts"
      #   run: |
      #     for file in apps/client/android/app/build/outputs/apk/debug/*.apk; do
      #       echo "Uploading $file to R2"
      #       bun run packages/scripts/upload-client-artifacts.ts --src "$(realpath $file)" --dest "debug/android/${{ steps.debug-runtimeversion.outputs.hash }}/$(basename $file)"
      #     done

      #     for file in apps/client/android/app/build/outputs/bundle/debug/*.aab; do
      #       echo "Uploading $file to R2"
      #       bun run packages/scripts/upload-client-artifacts.ts --src "$(realpath $file)" --dest "debug/android/${{ steps.debug-runtimeversion.outputs.hash }}/$(basename $file)"
      #     done

      # - name: Debug Android App APK Links
      #   run: |
      #     echo "Debug Android App APK Links" >> $GITHUB_STEP_SUMMARY
      #     echo "- [arm64-v8a](https://artifacts.voel.app/debug/android/${{ steps.debug-runtimeversion.outputs.hash }}/app-arm64-v8a-debug.apk)" >> $GITHUB_STEP_SUMMARY
      #     echo "- [armeabi-v7a](https://artifacts.voel.app/debug/android/${{ steps.debug-runtimeversion.outputs.hash }}/app-armeabi-v7a-debug.apk)" >> $GITHUB_STEP_SUMMARY
      #     echo "- [x86](https://artifacts.voel.app/debug/android/${{ steps.debug-runtimeversion.outputs.hash }}/app-x86-debug.apk)" >> $GITHUB_STEP_SUMMARY
      #     echo "- [x86_64](https://artifacts.voel.app/debug/android/${{ steps.debug-runtimeversion.outputs.hash }}/app-x86_64-debug.apk)" >> $GITHUB_STEP_SUMMARY

      - name: Generate Native Preview Module
        if: steps.preview-runtimeversion.outputs.exists == 'false'
        working-directory: apps/client
        run: bun run prebuild:preview --platform android --clean

      - name: Build Android Preview Assets
        if: steps.preview-runtimeversion.outputs.exists == 'false'
        working-directory: apps/client/android
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease --build-cache --parallel --stacktrace -Dorg.gradle.jvmargs=-Xmx6144M # build apk
        #  ./gradlew bundleRelease --build-cache --parallel --stacktrace -Dorg.gradle.jvmargs=-Xmx6144M # build aab
        env:
          RELEASE_CHANNEL: preview
          VOEL_ANDROID_APP_JKS_PASSWORD: ${{ secrets.VOEL_ANDROID_APP_JKS_PASSWORD }}
          CMAKE_C_COMPILER_LAUNCHER: /usr/bin/ccache
          CMAKE_CXX_COMPILER_LAUNCHER: /usr/bin/ccache
          NODE_ENV: production

      - name: Upload Preview Android Assets
        if: steps.preview-runtimeversion.outputs.exists == 'false'
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_ENDPOINT: "https://2365912f37ae5914a23644799e325b04.r2.cloudflarestorage.com"
          R2_BUCKET: "voel-gh-actions-artifacts"
        run: |
          for file in apps/client/android/app/build/outputs/apk/release/*.apk; do
            echo "Uploading $file to R2"
            bun run packages/scripts/upload-client-artifacts.ts --src $(realpath $file) --dest preview/android/${{ steps.preview-runtimeversion.outputs.hash }}/$(basename $file)
          done

      #     for file in apps/client/android/app/build/outputs/bundle/release/*.aab; do
      #       echo "Uploading $file to R2"
      #       bun run packages/scripts/upload-client-artifacts.ts --src "$(realpath $file)" --dest "preview/android/${{ steps.preview-runtimeversion.outputs.hash }}/$(basename $file)"
      #     done

      - name: Preview Android App APK Links
        run: |
          echo "Preview Android App APK Links" >> $GITHUB_STEP_SUMMARY
          echo "- [arm64-v8a](https://artifacts.voel.app/preview/android/${{ steps.preview-runtimeversion.outputs.hash }}/app-arm64-v8a-release.apk)" >> $GITHUB_STEP_SUMMARY
          echo "- [armeabi-v7a](https://artifacts.voel.app/preview/android/${{ steps.preview-runtimeversion.outputs.hash }}/app-armeabi-v7a-release.apk)" >> $GITHUB_STEP_SUMMARY
          echo "- [x86](https://artifacts.voel.app/preview/android/${{ steps.preview-runtimeversion.outputs.hash }}/app-x86-release.apk)" >> $GITHUB_STEP_SUMMARY
          echo "- [x86_64](https://artifacts.voel.app/preview/android/${{ steps.preview-runtimeversion.outputs.hash }}/app-x86_64-release.apk)" >> $GITHUB_STEP_SUMMARY

  ota-update:
    runs-on: self-hosted

    needs:
      - should-skip

    if: needs.should-skip.outputs.should_skip != 'true'

    steps:
      - name: Checkout repo
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: "lts/*"

      - name: Find Metro Cache
        id: metro-cache-dir-path
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          result-encoding: string
          script: |
            const os = require('os');
            const path = require('path');
            return path.join(os.tmpdir(), 'metro-cache');

      - name: Restore Metro cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ${{ steps.metro-cache-dir-path.outputs.result }}
          key: metro-cache-${{ runner.os }}-${{ github.job }}-${{ github.sha }}
          restore-keys: |
            metro-cache-${{ runner.os }}-${{ github.job }}-

      - name: Publish Debug OTA Update
        working-directory: apps/client
        run: bun run export
        env:
          RELEASE_CHANNEL: development
          VOEL_ANDROID_APP_JKS_PASSWORD: ${{ secrets.VOEL_ANDROID_APP_JKS_PASSWORD }}
          NODE_ENV: development
          EXPO_TOKEN: ${{ secrets.EOAS_EXPO_TOKEN }}

      - name: Publish Preview OTA Update
        working-directory: apps/client
        run: bun run export:preview
        env:
          RELEASE_CHANNEL: preview
          VOEL_ANDROID_APP_JKS_PASSWORD: ${{ secrets.VOEL_ANDROID_APP_JKS_PASSWORD }}
          NODE_ENV: production
          EXPO_TOKEN: ${{ secrets.EOAS_EXPO_TOKEN }}
