name: Cleanup PR Packages

on:
  pull_request:
    types:
      - closed

concurrency:
  # Only cancel in-progress runs for pull_request events, this prevents canceling workflows against main or tags
  # A pull_request will reuse the same group thus enabling cancellation, all others receive a unique run_id
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  cleanup-pr-packages:
    runs-on: self-hosted

    permissions:
      packages: write

    steps:
      - name: Delete all Server packages from this PR
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
        with:
          delete-tags: pr-${{ github.event.pull_request.number }},pr-${{ github.event.pull_request.number }}-*
