name: Cleanup Packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

concurrency:
  # Only cancel in-progress runs for pull_request events, this prevents canceling workflows against main or tags
  # A pull_request will reuse the same group thus enabling cancellation, all others receive a unique run_id
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  cleanup-packages:
    runs-on: self-hosted

    permissions:
      packages: write

    steps:
      - name: Delete all except latest 10 package versions
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5
        with:
          package-name: voel
          package-type: container
          min-versions-to-keep: 10
          ignore-versions: '^(edge|pr-\d+)$'
