name: Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
      - name: Run tests
        run: bun run --filter '*' --bun test
