name: Test

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
    tags:
      - "v*"
  merge_group:

concurrency:
  # Only cancel in-progress runs for pull_request events, this prevents canceling workflows against main or tags
  # A pull_request will reuse the same group thus enabling cancellation, all others receive a unique run_id
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
      - name: Run tests
        run: bun test --only-failures
